// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Studuent.proto

package com.protobuf.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protobuf.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 1;</code>
   */
  String getRealName();
  /**
   * <code>string realName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
