// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Studuent.proto

package com.protobuf.proto;

public interface MyStudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protobuf.proto.MyStudent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string city = 3;</code>
   */
  String getCity();
  /**
   * <code>string city = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
